
function CDDA_LoadSandboxDefaults()
	CDDA_Sandbox = getSandboxOptions():getOptionByName("CDDAZombies.SandBox"):getValue()
	CDDA_OutfitZ = getSandboxOptions():getOptionByName("CDDAZombies.OutfitZ"):getValue()
	CDDA_NameTag = getSandboxOptions():getOptionByName("CDDAZombies.NameTag"):getValue()
	SBO_Speed = getSandboxOptions():getOptionByName("ZombieLore.Speed"):getValue()
	SBO_Strength = getSandboxOptions():getOptionByName("ZombieLore.Strength"):getValue()
	--SBO_Toughness = getSandboxOptions():getOptionByName("ZombieLore.Toughness"):getValue()
	SBO_Cognition = getSandboxOptions():getOptionByName("ZombieLore.Cognition"):getValue()
	--SBO_Transmission = getSandboxOptions():getOptionByName("ZombieLore.Transmission"):getValue()
	--SBO_Memory = getSandboxOptions():getOptionByName("ZombieLore.Memory"):getValue()
	--SBO_Sight = getSandboxOptions():getOptionByName("ZombieLore.Sight"):getValue()
	--SBO_Hearing = getSandboxOptions():getOptionByName("ZombieLore.Hearing"):getValue()
	CDDA_ZombieInit()
end

function CDDA_SaveSandboxDefaults()
	if SBO_Speed then
		getSandboxOptions():set("ZombieLore.Speed", SBO_Speed)
		getSandboxOptions():set("ZombieLore.Strength",SBO_Strength)
		--getSandboxOptions():set("ZombieLore.Toughness",SBO_Toughness)
		getSandboxOptions():set("ZombieLore.Cognition",SBO_Cognition)
		--getSandboxOptions():set("ZombieLore.Transmission",SBO_Transmission)
		--getSandboxOptions():set("ZombieLore.Memory",SBO_Memory)
		--getSandboxOptions():set("ZombieLore.Sight",SBO_Sight)
		--getSandboxOptions():set("ZombieLore.Hearing",SBO_Hearing)
	end
end

function CDDA_CheckOnSpawn(_Speed, _Strength, _Toughness, _Cognition, _Transmission, _Memory, _Sight, _Hearing)
	if not CDDA_Sandbox then
		if _Speed % 2^SBO_Speed < 2^(SBO_Speed-1) then
			return false
		end
		if _Strength % 2^SBO_Strength < 2^(SBO_Strength-1) then
			return false
		end
		--if _Toughness % 2^SBO_Toughness < 2^(SBO_Toughness-1) then
		--	return false
		--end
		if _Cognition % 2^SBO_Cognition < 2^(SBO_Cognition-1) then
			return false
		end
		--if _Transmission % 2^SBO_Transmission < 2^(SBO_Transmission-1) then
		--	return false
		--end
		--if _Memory % 2^SBO_Memory < 2^(SBO_Memory-1) then
		--	return false
		--end
		--if _Sight % 2^SBO_Sight < 2^(SBO_Sight-1) then
		--	return false
		--end
		--if _Hearing % 2^SBO_Hearing < 2^(SBO_Hearing-1) then
		--	return false
		--end
	end
	return true
end

function CDDA_SetZombies()
	CDDA_Zombies = 
	{
		{--1爬尸
			chance = SandboxVars.CDDAZombies.Crawler,
			name = "IGUI_CDDA_CrawlerZ",
			walktype = 4,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {255, 105, 180,},
			outline = {0, 128, 0,},
			spawn = true,

		},
		{--2骷髅
			chance = SandboxVars.CDDAZombies.Skeleton,
			name = "IGUI_CDDA_SkeletonZ",
			walktype = 2,
			strength = 3,
			--toughness = 3,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 0.5,
			skeleton = true,
			color = {255, 255, 255,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(14,15,15,15,15,15,7,7),
			evo = {4},
		},
		{--3野性追猎者
			chance = SandboxVars.CDDAZombies.Feral,
			name = "IGUI_CDDA_RunnerZ",
			walktype = 1,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {165, 42, 42,},
			outline = {255, 255, 255,},
			spawn = CDDA_CheckOnSpawn(9,15,15,15,15,15,7,7),
			evo = {8},
			starthour = SandboxVars.CDDAZombies.FeralStartHour,
			endhour   = SandboxVars.CDDAZombies.FeralEndHour,
		},
		{--4骷髅追猎者
			chance = SandboxVars.CDDAZombies.SkeletonFeral,
			name = "IGUI_CDDA_SkeletonRunnerZ",
			walktype = 1,
			strength = 3,
			--toughness = 3,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 0.5,
			skeleton = true,
			color = {255, 255, 255,},
			outline = {165, 42, 42,},
			spawn = CDDA_CheckOnSpawn(9,15,15,15,15,15,7,7),
			starthour = SandboxVars.CDDAZombies.SkeletonFeralStartHour,
			endhour   = SandboxVars.CDDAZombies.SkeletonFeralEndHour,
		},
		{--5健壮丧尸
			chance = SandboxVars.CDDAZombies.Tough,
			name = "IGUI_CDDA_StrongZ",
			walktype = 2,
			strength = 1,
			--toughness = 1,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1.5,
			keepstand = true,
			color = {240, 112, 75,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(14,9,9,15,15,15,7,7),
			evo = {3,9},
		},
		{--6肥胖丧尸
			chance = SandboxVars.CDDAZombies.Fat,
			name = "IGUI_CDDA_FatZ",
			walktype = 3,
			strength = 2,
			--toughness = 1,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 2,
			keepstand = true,
			color = {0, 112, 0,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(12,15,15,15,15,15,7,7),
			evo = {12,13},
		},
		{--7巫妖丧尸
			chance = SandboxVars.CDDAZombies.Necromancer,
			name = "IGUI_CDDA_WitchZ",
			alert = true,
			walktype = 3,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			funcpermin = "Reanim",
			color = {169, 169, 169,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(12,15,15,15,15,15,7,7),
			starthour = SandboxVars.CDDAZombies.NecromancerStartHour,
			endhour   = SandboxVars.CDDAZombies.NecromancerEndHour,
		},
		{--8狂暴丧尸兽
			chance = SandboxVars.CDDAZombies.Brute,
			name = "IGUI_CDDA_BruteZ",
			alert = true,
			walktype = 1,
			strength = 1,
			--toughness = 1,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 3,
			keepstand = true,
			functions = "Push",
			color = {255, 0, 0,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(9,9,9,15,15,15,7,7),
		},
		{--9摔跤手丧尸
			chance = SandboxVars.CDDAZombies.Wrestler,
			name = "IGUI_CDDA_WrestlerZ",
			alert = true,
			walktype = 2,
			strength = 1,
			--toughness = 1,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 3,
			keepstand = true,
			functions = "Push",
			color = {255, 0, 0,},
			outline = {255, 255, 255,},
			spawn = CDDA_CheckOnSpawn(14,9,9,15,15,15,7,7),
			evo = {8},
		},
		{--10尖叫丧尸
			chance = SandboxVars.CDDAZombies.Screamer,
			name = "IGUI_CDDA_ScreamerZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			funcpermin = "Scream",
			color = {139, 0, 81,},
			outline = {0, 0, 0,},
			spawn = true,
			starthour = SandboxVars.CDDAZombies.ScreamerStartHour,
			endhour   = SandboxVars.CDDAZombies.ScreamerEndHour,
		},
		{--11幸存者丧尸
			chance = 0,--SandboxVars.CDDAZombies.Survivor,
			name = "IGUI_CDDA_SurvivorZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 1,
			--noteeth= true,
			--memory = 1,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {240, 128, 128,},
			outline = {0, 128, 0,},
			outfit = {"Survivalist", "Survivalist02", "Survivalist03"},
			spawn = false,
		},
		{--12循声者丧尸
			chance = SandboxVars.CDDAZombies.Listener,
			name = "IGUI_CDDA_ListenerZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 3,
			--hearing = 1,
			HP = 1,
			color = {144, 238, 144,},
			outline = {0, 0, 0,},
			spawn = false,
			evo = {5},
			starthour = SandboxVars.CDDAZombies.ListenerStartHour,
			endhour   = SandboxVars.CDDAZombies.ListenerEndHour,
		},
		--{--13流涎啃噬者
		--	chance = SandboxVars.CDDAZombies.Biter,
		--	name = "IGUI_CDDA_BiterZ",
		--	walktype = 2,
		--	strength = 2,
		--	--toughness = 2,
		--	cognition = 3,
		--	--noteeth= false,
		--	--memory = 2,
		--	--sight = 2,
		--	--hearing = 2,
		--	HP = 1,
		--	color = {0, 139, 139,},
		--	outline = {0, 134, 31,},
		--	spawn = false,
		--},
		{--13肉钩丧尸
			chance = SandboxVars.CDDAZombies.Grabber,
			name = "IGUI_CDDA_GrabberZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {0, 139, 139,},
			outline = {0, 0, 0,},
			funccollide = "Grab",
			functions = "GrabOnAttack",
			spawn = true,
			evo = {5},
		},
		{--14警察丧尸
			chance = 0,
			name = "IGUI_CDDA_CopZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {0, 0, 255,},
			outline = {0, 0, 0,},
			outfit = {"Police", "PoliceState"},
			spawn = CDDA_OutfitZ,
		},
		{--15消防员丧尸
			chance = 0,
			name = "IGUI_CDDA_FiremanZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1.5,
			color = {255, 255, 0,},
			outline = {0, 0, 0,},
			outfit = {"Fireman", "FiremanFullSuit",},
			functions = "EndFire",
			spawn = CDDA_OutfitZ,
		},
		{--16士兵丧尸
			chance = 0,
			name = "IGUI_CDDA_SoldierZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 2,
			color = {144, 238, 144,},
			outline = {0, 128, 0,},
			outfit = {"ArmyCamoDesert","ArmyCamoGreen","PrivateMilitia"},
			spawn = CDDA_OutfitZ,
		},
		{--17儿童丧尸
			chance = 0,
			name = "IGUI_CDDA_ChildZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 0.7,
			color = {144, 238, 144,},
			outline = {0, 128, 0,},
			outfit = {"Student","Young",},
			funconhit = "Unhappy",
			spawn = CDDA_OutfitZ,
		},
		{--18防化员丧尸
			chance = 0,
			name = "IGUI_CDDA_HazmatZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1.5,
			color = {255, 255, 255,},
			outline = {0, 128, 0,},
			outfit = {"HazardSuit",},
			spawn = CDDA_OutfitZ,
		},
		{--19主宰丧尸
			chance = SandboxVars.CDDAZombies.Master,
			name = "IGUI_CDDA_MasterZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {255, 0, 0,},
			outline = {255, 105, 180,},
			funcpermin = "Upgrade",
			spawn = CDDA_CheckOnSpawn(12,15,15,15,15,15,7,7),
			starthour = SandboxVars.CDDAZombies.MasterStartHour,
			endhour   = SandboxVars.CDDAZombies.MasterEndHour,
		},
		{--20普通丧尸
			chance = SandboxVars.CDDAZombies.Normal,
			name = "IGUI_CDDA_NormalZ",
			walktype = 2,
			strength = 2,
			--toughness = 2,
			cognition = 3,
			--noteeth= true,
			--memory = 2,
			--sight = 2,
			--hearing = 2,
			HP = 1,
			color = {144, 238, 144,},
			outline = {0, 0, 0,},
			spawn = CDDA_CheckOnSpawn(14,14,14,15,15,15,7,7),
			evo = {12,13},
		},
	}
end

